// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45th-71MntImAUYEDTtqQ7kl6BnjoexQ',
    appId: '1:1077286284703:web:3019e475f409ce48bae1aa',
    messagingSenderId: '1077286284703',
    projectId: 'fir-hostin-5abae',
    authDomain: 'fir-hostin-5abae.firebaseapp.com',
    storageBucket: 'fir-hostin-5abae.appspot.com',
    measurementId: 'G-VG1H56T9WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWzRo0NqwI6ftKOyR2VqVuoaaxXEu_fY',
    appId: '1:1077286284703:android:ace18bb089c612c5bae1aa',
    messagingSenderId: '1077286284703',
    projectId: 'fir-hostin-5abae',
    storageBucket: 'fir-hostin-5abae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtkvPbthynHNqhXh6hGN3mXm8Cvk5x5k',
    appId: '1:1077286284703:ios:ae115cd6924fd25dbae1aa',
    messagingSenderId: '1077286284703',
    projectId: 'fir-hostin-5abae',
    storageBucket: 'fir-hostin-5abae.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtkvPbthynHNqhXh6hGN3mXm8Cvk5x5k',
    appId: '1:1077286284703:ios:090b653af226039fbae1aa',
    messagingSenderId: '1077286284703',
    projectId: 'fir-hostin-5abae',
    storageBucket: 'fir-hostin-5abae.appspot.com',
    iosBundleId: 'com.example.eComm.RunnerTests',
  );
}
